# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  name "kin"
  desc "A terminal-first snippet manager"
  homepage "https://github.com/kaizakin/kinctx"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kin"

  on_macos do
    on_intel do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_darwin_amd64.tar.gz"
      sha256 "59262e69b99693ff3eeefbff93ae73e35d82654d5a85794c69f07e43ed332272"
    end
    on_arm do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_darwin_arm64.tar.gz"
      sha256 "9f3793d4cea9b0c9934e285b839f064543cca7d748a83e2505bee1b08a32d003"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_linux_amd64.tar.gz"
      sha256 "b41b0a3438d4e2d32e82d48aed512c98ed20005f80c6f792b8bc78316c9bdc29"
    end
    on_arm do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_linux_arm64.tar.gz"
      sha256 "e30949ab5ac4927b7041065113f9a66b53d4bad9086f27ff9a3ee227487a6b26"
    end
  end

  # No zap stanza required
end
