# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  name "kin"
  desc "A terminal-first snippet manager"
  homepage "https://github.com/kaizakin/kinctx"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kin"

  on_macos do
    on_intel do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_darwin_amd64.tar.gz"
      sha256 "19593609deaecd1b8bc3d522f1d8465ef1ce8475f66f3c5597c22eaf117faeff"
    end
    on_arm do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_darwin_arm64.tar.gz"
      sha256 "c418792a91dbdd1714b15cd5484ab4634eda5c3ccaac317c88a6ea713a8a1cc0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_linux_amd64.tar.gz"
      sha256 "37a45f115855c50fe9cb1ceb9ea57ffc14d8db6a66fb4ae9e8e934ed62c45497"
    end
    on_arm do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_linux_arm64.tar.gz"
      sha256 "21552a23196987ced351c796dd9ec031767452ff99372e352367513ba08b8f94"
    end
  end

  # No zap stanza required
end
