# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  name "kin"
  desc "A terminal-first snippet manager"
  homepage "https://github.com/kaizakin/kinctx"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kin"

  on_macos do
    on_intel do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_darwin_amd64.tar.gz"
      sha256 "f2634fc3e52b14d987823aca62112ec039300d424c7d5eabcd5364b975b4b76d"
    end
    on_arm do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_darwin_arm64.tar.gz"
      sha256 "6abd5660243ffefcbecacd7b66ba322300911b5da6bdcf708b66165fc2256f3a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_linux_amd64.tar.gz"
      sha256 "b6b7e714f4a414718b2e98d32281bff458818ce1151a5fa38f517e7907fd9272"
    end
    on_arm do
      url "https://github.com/kaizakin/kinctx/releases/download/v#{version}/kinctx_#{version}_linux_arm64.tar.gz"
      sha256 "5d692f9f247568342dcea5da5fc90ffbd8b88faa7b2ddb7bd586e4754e049ad3"
    end
  end

  # No zap stanza required
end
